name: Go

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          version: '15.0.7'

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Build
        run: go build -v ./...

      - name: Test
        uses: robherley/go-test-action@v0.1.0
        with:
          testArguments: 'test/*'
